version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - MONGODB_DATABASE=${MONGODB_DATABASE}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DEEPFACE_MODEL=${DEEPFACE_MODEL}
      - DEEPFACE_DETECTOR=${DEEPFACE_DETECTOR}
      - VIDEODB_API_KEY=${VIDEODB_API_KEY}
      - VIDEODB_COLLECTION_ID=${VIDEODB_COLLECTION_ID}
    volumes:
      - ./backend:/app
    restart: unless-stopped

  frontend:
    build: ./react-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped