app = "smartvision-backend"
primary_region = "ord"

[build]

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[processes]
  app = "uvicorn main:app --host 0.0.0.0 --port 8000"

[[vm]]
  cpu_kind = "shared"
  cpus = 2
  memory_mb = 2048